language: c
compiler: gcc

sudo: required
dist: trusty

cache:
  - ccache
  - pip

env:
  - VALAC=valac-0.30
  #- VALAC=valac-0.30 VALAFLAGS=--fatal-warnings

addons:
  apt:
    sources:
      - sourceline: 'ppa:vala-team/ppa'
    packages:
      - gettext
      - libtool
      - intltool
      - libglib2.0-dev
      - libjson-glib-dev
      - libgee-0.8-dev
      - libvala-0.30-dev
      - libgsl0-dev
      - libsqlite0-dev
      - libxml2-dev
      - libmatheval-dev
      - libmodbus-dev
      - libcomedi-dev
      - libgirepository1.0-dev
      - valac-0.30
      - valgrind
      - python3-pip

before_install:
  - pip3 install --user cpp-coveralls
  - pip3 install meson
  - wget https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-linux.zip
  - unzip ninja-linux.zip -d ${HOME}/.local/bin

before_script:
  - meson _build
  - ninja -C _build -v

script: .ci/script.sh

after_success:
  - coveralls --exclude tests --gcov-options '\-lp'

notifications:
  email:
    - geoff.jay@gmail.com
