language: c
compiler: gcc

sudo: required
dist: trusty

env:
  global:
    - MAKE_CMD="make -j2"

script: .ci/script.sh

addons:
  apt:
    sources:
      - sourceline: 'ppa:vala-team/ppa'
    packages:
      - autoconf
      - autoconf-archive
      - automake
      - gettext
      - libtool
      - intltool
      - libglib2.0-dev
      - libjson-glib-dev
      - libgee-0.8-dev
      - libvala-0.30-dev
      - libgsl0-dev
      - libsqlite0-dev
      - libxml2-dev
      - libmatheval-dev
      - libmodbus-dev
      - libcomedi-dev
      - libgirepository1.0-dev
      - valac-0.30

notifications:
  email:
    - geoff.jay@gmail.com
