# Test the installation and removal of the Debian packages

FROM debian:buster

RUN apt update
RUN apt install --no-install-recommends -qq -y curl ca-certificates

RUN curl -v https://packagecloud.io/install/repositories/coanda/public/script.deb.sh | bash

RUN apt install libcld-1.0-dev -y
RUN apt remove libcld-1.0-dev -y

RUN apt remove libcld-1.0-0 -y
RUN apt install libcld-1.0-0 -y
RUN apt remove libcld-1.0-0 -y

RUN apt remove gir1.2-cld-1.0 -y
RUN apt install gir1.2-cld-1.0 -y
RUN apt remove gir1.2-cld-1.0 -y
