#!/bin/bash

if [ "$1" = install ]; then
    # example:
    #for f in file1 file2; do
    #   dpkg-divert --package libcld --rename --add /usr/share/libcld/$f
    #done
    echo "No pre-installation steps yet"
fi
